### ISSUE TITLE
低70行你写的有问题吧...

### ISSUE THREAD

**Issue by JoshuaFeng5** [DengkeJ/WebViewProgress#1]
`- (void)setProgressColor:(UIColor *)progressColor {
    _progressColor = progressColor;
//    if (_progressStyle & DKProgressStyle_Noraml) {
//        self.strokeColor = progressColor.CGColor;
//    } else {
//        self.progressStyle = DKProgressStyle_Gradual;
//    }
    if (_progressStyle == DKProgressStyle_Noraml) {
        self.strokeColor = progressColor.CGColor;
    } else {
        self.progressStyle = DKProgressStyle_Gradual;
    }
}`

这样改就好了`

**Comment by DengkeJ** [comment]
确实是不对，应该是之前笔误，谢谢提醒
